//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.tb_KuCunRecords {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblHuoJiaHao;
	protected global::System.Web.UI.WebControls.Label lblCengHao;
	protected global::System.Web.UI.WebControls.Label lblLieHao;
	protected global::System.Web.UI.WebControls.Label lblBianMa;
	protected global::System.Web.UI.WebControls.Label lblMingCheng;
	protected global::System.Web.UI.WebControls.Label lblGuiGe;
	protected global::System.Web.UI.WebControls.Label lblXingHao;
	protected global::System.Web.UI.WebControls.Label lblHeTongHao;
	protected global::System.Web.UI.WebControls.Label lblX;
	protected global::System.Web.UI.WebControls.Label lblY;
	protected global::System.Web.UI.WebControls.Label lblZ;
	protected global::System.Web.UI.WebControls.Label lblRuKuTime;
	protected global::System.Web.UI.WebControls.Label lblChuKuTime;
	protected global::System.Web.UI.WebControls.Label lblCaoZuoYuan;


       
    }
}
