//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.tb_KuWeiDetail {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblHuoJiaHao;
	protected global::System.Web.UI.WebControls.Label lblCengHao;
	protected global::System.Web.UI.WebControls.Label lblLieHao;
	protected global::System.Web.UI.WebControls.Label lblXuHao;
		protected global::System.Web.UI.WebControls.TextBox txtRuKuTime;
		protected global::System.Web.UI.WebControls.TextBox txtCaoZuoYuan;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
